import type { SymbolCategory, SymbolItem } from '@/types';

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    id: 'greek',
    label: '希腊字母',
    symbols: [
      { latex: '\\alpha', label: 'α', description: 'Alpha' },
      { latex: '\\beta', label: 'β', description: 'Beta' },
      { latex: '\\gamma', label: 'γ', description: 'Gamma' },
      { latex: '\\delta', label: 'δ', description: 'Delta' },
      { latex: '\\epsilon', label: 'ε', description: 'Epsilon' },
      { latex: '\\varepsilon', label: 'ε', description: 'Varepsilon' },
      { latex: '\\zeta', label: 'ζ', description: 'Zeta' },
      { latex: '\\eta', label: 'η', description: 'Eta' },
      { latex: '\\theta', label: 'θ', description: 'Theta' },
      { latex: '\\vartheta', label: 'ϑ', description: 'Vartheta' },
      { latex: '\\iota', label: 'ι', description: 'Iota' },
      { latex: '\\kappa', label: 'κ', description: 'Kappa' },
      { latex: '\\lambda', label: 'λ', description: 'Lambda' },
      { latex: '\\mu', label: 'μ', description: 'Mu' },
      { latex: '\\nu', label: 'ν', description: 'Nu' },
      { latex: '\\xi', label: 'ξ', description: 'Xi' },
      { latex: '\\pi', label: 'π', description: 'Pi' },
      { latex: '\\varpi', label: 'ϖ', description: 'Varpi' },
      { latex: '\\rho', label: 'ρ', description: 'Rho' },
      { latex: '\\varrho', label: 'ϱ', description: 'Varrho' },
      { latex: '\\sigma', label: 'σ', description: 'Sigma' },
      { latex: '\\varsigma', label: 'ς', description: 'Varsigma' },
      { latex: '\\tau', label: 'τ', description: 'Tau' },
      { latex: '\\upsilon', label: 'υ', description: 'Upsilon' },
      { latex: '\\phi', label: 'φ', description: 'Phi' },
      { latex: '\\varphi', label: 'ϕ', description: 'Varphi' },
      { latex: '\\chi', label: 'χ', description: 'Chi' },
      { latex: '\\psi', label: 'ψ', description: 'Psi' },
      { latex: '\\omega', label: 'ω', description: 'Omega' },
      { latex: '\\Gamma', label: 'Γ', description: 'Gamma (upper)' },
      { latex: '\\Delta', label: 'Δ', description: 'Delta (upper)' },
      { latex: '\\Theta', label: 'Θ', description: 'Theta (upper)' },
      { latex: '\\Lambda', label: 'Λ', description: 'Lambda (upper)' },
      { latex: '\\Xi', label: 'Ξ', description: 'Xi (upper)' },
      { latex: '\\Pi', label: 'Π', description: 'Pi (upper)' },
      { latex: '\\Sigma', label: 'Σ', description: 'Sigma (upper)' },
      { latex: '\\Phi', label: 'Φ', description: 'Phi (upper)' },
      { latex: '\\Psi', label: 'Ψ', description: 'Psi (upper)' },
      { latex: '\\Omega', label: 'Ω', description: 'Omega (upper)' },
    ],
  },
  {
    id: 'operators',
    label: '运算符',
    symbols: [
      { latex: '\\frac{a}{b}', label: 'a/b' },
      { latex: '\\sqrt{x}', label: '√x' },
      { latex: '\\sqrt[n]{x}', label: 'ⁿ√x' },
      { latex: '\\sum_{i=1}^{n}', label: '∑' },
      { latex: '\\prod_{i=1}^{n}', label: '∏' },
      { latex: '\\int_{a}^{b}', label: '∫' },
      { latex: '\\iint', label: '∬' },
      { latex: '\\iiint', label: '∭' },
      { latex: '\\oint', label: '∮' },
      { latex: '\\lim_{x \\to 0}', label: 'lim' },
      { latex: '\\log', label: 'log' },
      { latex: '\\ln', label: 'ln' },
      { latex: '\\sin', label: 'sin' },
      { latex: '\\cos', label: 'cos' },
      { latex: '\\tan', label: 'tan' },
      { latex: '\\pm', label: '±' },
      { latex: '\\mp', label: '∓' },
      { latex: '\\times', label: '×' },
      { latex: '\\div', label: '÷' },
      { latex: '\\cdot', label: '·' },
      { latex: '\\circ', label: '∘' },
      { latex: '\\ast', label: '∗' },
      { latex: '\\star', label: '⋆' },
    ],
  },
  {
    id: 'arrows',
    label: '箭头',
    symbols: [
      { latex: '\\to', label: '→' },
      { latex: '\\rightarrow', label: '→' },
      { latex: '\\leftarrow', label: '←' },
      { latex: '\\Rightarrow', label: '⇒' },
      { latex: '\\Leftarrow', label: '⇐' },
      { latex: '\\Leftrightarrow', label: '⇔' },
      { latex: '\\mapsto', label: '↦' },
      { latex: '\\longrightarrow', label: '⟶' },
      { latex: '\\hookrightarrow', label: '↪' },
      { latex: '\\rightharpoonup', label: '⇀' },
      { latex: '\\rightleftharpoons', label: '⇌' },
      { latex: '\\uparrow', label: '↑' },
      { latex: '\\downarrow', label: '↓' },
      { latex: '\\updownarrow', label: '↕' },
      { latex: '\\nearrow', label: '↗' },
      { latex: '\\searrow', label: '↘' },
    ],
  },
  {
    id: 'set-theory',
    label: '集合论',
    symbols: [
      { latex: '\\in', label: '∈' },
      { latex: '\\notin', label: '∉' },
      { latex: '\\subset', label: '⊂' },
      { latex: '\\supset', label: '⊃' },
      { latex: '\\subseteq', label: '⊆' },
      { latex: '\\supseteq', label: '⊇' },
      { latex: '\\cup', label: '∪' },
      { latex: '\\cap', label: '∩' },
      { latex: '\\emptyset', label: '∅' },
      { latex: '\\varnothing', label: '∅' },
      { latex: '\\mathbb{N}', label: 'ℕ' },
      { latex: '\\mathbb{Z}', label: 'ℤ' },
      { latex: '\\mathbb{Q}', label: 'ℚ' },
      { latex: '\\mathbb{R}', label: 'ℝ' },
      { latex: '\\mathbb{C}', label: 'ℂ' },
      { latex: '\\forall', label: '∀' },
      { latex: '\\exists', label: '∃' },
      { latex: '\\nexists', label: '∄' },
      { latex: '\\nabla', label: '∇' },
      { latex: '\\partial', label: '∂' },
    ],
  },
  {
    id: 'matrices',
    label: '矩阵模板',
    symbols: [
      { latex: '\\begin{matrix} a & b \\\\ c & d \\end{matrix}', label: 'matrix' },
      { latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', label: 'pmatrix' },
      { latex: '\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}', label: 'bmatrix' },
      { latex: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}', label: 'vmatrix' },
      { latex: '\\begin{cases} x & \\text{if } a \\\\ y & \\text{otherwise} \\end{cases}', label: 'cases' },
      { latex: '\\begin{aligned} x &= a + b \\\\ y &= c + d \\end{aligned}', label: 'aligned' },
    ],
  },
  {
    id: 'integrals-sums',
    label: '积分/求和',
    symbols: [
      { latex: '\\int', label: '∫' },
      { latex: '\\int_{a}^{b}', label: '∫ₐᵇ' },
      { latex: '\\iint', label: '∬' },
      { latex: '\\iiint', label: '∭' },
      { latex: '\\oint', label: '∮' },
      { latex: '\\sum', label: '∑' },
      { latex: '\\sum_{i=1}^{n}', label: '∑ᵢ₌₁ⁿ' },
      { latex: '\\prod', label: '∏' },
      { latex: '\\prod_{i=1}^{n}', label: '∏ᵢ₌₁ⁿ' },
      { latex: '\\lim', label: 'lim' },
      { latex: '\\lim_{x \\to \\infty}', label: 'limₓ→∞' },
    ],
  },
  {
    id: 'relations',
    label: '关系符号',
    symbols: [
      { latex: '\\leq', label: '≤' },
      { latex: '\\geq', label: '≥' },
      { latex: '\\ll', label: '≪' },
      { latex: '\\gg', label: '≫' },
      { latex: '\\approx', label: '≈' },
      { latex: '\\equiv', label: '≡' },
      { latex: '\\sim', label: '∼' },
      { latex: '\\simeq', label: '≃' },
      { latex: '\\cong', label: '≅' },
      { latex: '\\neq', label: '≠' },
      { latex: '\\propto', label: '∝' },
      { latex: '\\perp', label: '⊥' },
      { latex: '\\parallel', label: '∥' },
    ],
  },
  {
    id: 'accents',
    label: '重音/装饰',
    symbols: [
      { latex: '\\hat{a}', label: 'â' },
      { latex: '\\bar{a}', label: 'ā' },
      { latex: '\\tilde{a}', label: 'ã' },
      { latex: '\\dot{a}', label: 'ȧ' },
      { latex: '\\ddot{a}', label: 'ä' },
      { latex: '\\vec{a}', label: 'a⃗' },
      { latex: '\\widehat{ab}', label: 'ab̂' },
      { latex: '\\overline{ab}', label: 'ab̅' },
      { latex: '\\underline{ab}', label: 'ab̲' },
      { latex: '\\overbrace{ab}', label: 'ab⏞' },
      { latex: '\\underbrace{ab}', label: 'ab⏟' },
    ],
  },
];

export function getAllSymbols(): SymbolItem[] {
  return SYMBOL_CATEGORIES.flatMap((cat) => cat.symbols);
}

export function searchSymbols(query: string): SymbolItem[] {
  const q = query.toLowerCase();
  return getAllSymbols().filter(
    (s) =>
      s.label.toLowerCase().includes(q) ||
      s.latex.toLowerCase().includes(q) ||
      (s.description ?? '').toLowerCase().includes(q),
  );
}

export function getCategoryById(id: string): SymbolCategory | undefined {
  return SYMBOL_CATEGORIES.find((c) => c.id === id);
}

// LaTeX autocomplete data
export const AUTOCOMPLETE_COMMANDS: { label: string; insert: string; detail?: string }[] = [
  { label: '\\alpha', insert: '\\alpha', detail: 'α' },
  { label: '\\beta', insert: '\\beta', detail: 'β' },
  { label: '\\gamma', insert: '\\gamma', detail: 'γ' },
  { label: '\\delta', insert: '\\delta', detail: 'δ' },
  { label: '\\epsilon', insert: '\\epsilon', detail: 'ε' },
  { label: '\\zeta', insert: '\\zeta', detail: 'ζ' },
  { label: '\\eta', insert: '\\eta', detail: 'η' },
  { label: '\\theta', insert: '\\theta', detail: 'θ' },
  { label: '\\iota', insert: '\\iota', detail: 'ι' },
  { label: '\\kappa', insert: '\\kappa', detail: 'κ' },
  { label: '\\lambda', insert: '\\lambda', detail: 'λ' },
  { label: '\\mu', insert: '\\mu', detail: 'μ' },
  { label: '\\nu', insert: '\\nu', detail: 'ν' },
  { label: '\\xi', insert: '\\xi', detail: 'ξ' },
  { label: '\\pi', insert: '\\pi', detail: 'π' },
  { label: '\\rho', insert: '\\rho', detail: 'ρ' },
  { label: '\\sigma', insert: '\\sigma', detail: 'σ' },
  { label: '\\tau', insert: '\\tau', detail: 'τ' },
  { label: '\\upsilon', insert: '\\upsilon', detail: 'υ' },
  { label: '\\phi', insert: '\\phi', detail: 'φ' },
  { label: '\\chi', insert: '\\chi', detail: 'χ' },
  { label: '\\psi', insert: '\\psi', detail: 'ψ' },
  { label: '\\omega', insert: '\\omega', detail: 'ω' },
  { label: '\\Gamma', insert: '\\Gamma', detail: 'Γ' },
  { label: '\\Delta', insert: '\\Delta', detail: 'Δ' },
  { label: '\\Theta', insert: '\\Theta', detail: 'Θ' },
  { label: '\\Lambda', insert: '\\Lambda', detail: 'Λ' },
  { label: '\\Xi', insert: '\\Xi', detail: 'Ξ' },
  { label: '\\Pi', insert: '\\Pi', detail: 'Π' },
  { label: '\\Sigma', insert: '\\Sigma', detail: 'Σ' },
  { label: '\\Phi', insert: '\\Phi', detail: 'Φ' },
  { label: '\\Psi', insert: '\\Psi', detail: 'Ψ' },
  { label: '\\Omega', insert: '\\Omega', detail: 'Ω' },
  { label: '\\frac', insert: '\\frac{}{}', detail: '分数' },
  { label: '\\sqrt', insert: '\\sqrt{}', detail: '平方根' },
  { label: '\\sqrt[n]', insert: '\\sqrt[]{}', detail: 'n次根' },
  { label: '\\sum', insert: '\\sum_{}^{}', detail: '求和' },
  { label: '\\int', insert: '\\int_{}^{}', detail: '积分' },
  { label: '\\iint', insert: '\\iint_{}^{}', detail: '二重积分' },
  { label: '\\iiint', insert: '\\iiint_{}^{}', detail: '三重积分' },
  { label: '\\prod', insert: '\\prod_{}^{}', detail: '乘积' },
  { label: '\\lim', insert: '\\lim_{}', detail: '极限' },
  { label: '\\to', insert: '\\to', detail: '→' },
  { label: '\\rightarrow', insert: '\\rightarrow', detail: '→' },
  { label: '\\leftarrow', insert: '\\leftarrow', detail: '←' },
  { label: '\\Rightarrow', insert: '\\Rightarrow', detail: '⇒' },
  { label: '\\Leftrightarrow', insert: '\\Leftrightarrow', detail: '⇔' },
  { label: '\\mapsto', insert: '\\mapsto', detail: '↦' },
  { label: '\\infty', insert: '\\infty', detail: '∞' },
  { label: '\\partial', insert: '\\partial', detail: '∂' },
  { label: '\\nabla', insert: '\\nabla', detail: '∇' },
  { label: '\\forall', insert: '\\forall', detail: '∀' },
  { label: '\\exists', insert: '\\exists', detail: '∃' },
  { label: '\\in', insert: '\\in', detail: '∈' },
  { label: '\\notin', insert: '\\notin', detail: '∉' },
  { label: '\\subset', insert: '\\subset', detail: '⊂' },
  { label: '\\supset', insert: '\\supset', detail: '⊃' },
  { label: '\\subseteq', insert: '\\subseteq', detail: '⊆' },
  { label: '\\cup', insert: '\\cup', detail: '∪' },
  { label: '\\cap', insert: '\\cap', detail: '∩' },
  { label: '\\emptyset', insert: '\\emptyset', detail: '∅' },
  { label: '\\mathbb', insert: '\\mathbb{}', detail: '黑板粗体' },
  { label: '\\mathcal', insert: '\\mathcal{}', detail: '花体' },
  { label: '\\mathbf', insert: '\\mathbf{}', detail: '粗体' },
  { label: '\\textrm', insert: '\\textrm{}', detail: '罗马体' },
  { label: '\\text', insert: '\\text{}', detail: '文本' },
  { label: '\\begin', insert: '\\begin{}', detail: '环境开始' },
  { label: '\\end', insert: '\\end{}', detail: '环境结束' },
  { label: '\\begin{pmatrix}', insert: '\\begin{pmatrix} & \\\\ & \\end{pmatrix}', detail: '矩阵 ()' },
  { label: '\\begin{bmatrix}', insert: '\\begin{bmatrix} & \\\\ & \\end{bmatrix}', detail: '矩阵 []' },
  { label: '\\begin{cases}', insert: '\\begin{cases} & \\\\ & \\end{cases}', detail: '分段函数' },
  { label: '\\begin{aligned}', insert: '\\begin{aligned} & \\\\ & \\end{aligned}', detail: '对齐' },
  { label: '\\overline', insert: '\\overline{}', detail: '上划线' },
  { label: '\\underline', insert: '\\underline{}', detail: '下划线' },
  { label: '\\hat', insert: '\\hat{}', detail: 'hat 重音' },
  { label: '\\tilde', insert: '\\tilde{}', detail: 'tilde 重音' },
  { label: '\\vec', insert: '\\vec{}', detail: '向量' },
  { label: '\\dot', insert: '\\dot{}', detail: '点' },
  { label: '\\ddot', insert: '\\ddot{}', detail: '两点' },
];
